config/routes.rb
Rails.application.routes.draw do

  resources :usercodes
  root 'static_pages#home'
  get 'sessions/new'
  get 'users/new'
  get 'team' => 'static_pages#team'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'check_js_code' => 'static_pages#check_js_code'
  delete 'logout' => 'sessions#destroy'
  resources :usercodes
  resources :users

  

end

app/models/usercode.rb
class Usercode < ActiveRecord::Base
	belongs_to :user
end

app/controllers/usercodes_controller.rb
class UsercodesController < ApplicationController
  before_action :set_usercode, only: [:show, :edit, :update, :destroy]

  # GET /usercodes
  # GET /usercodes.json
  def index
    @usercodes = Usercode.where(user_id: session[:user_id])
  end

  # GET /usercodes/1
  # GET /usercodes/1.json
  def show
  end

  # GET /usercodes/new
  def new
    @usercode = Usercode.new
  end

  # GET /usercodes/1/edit
  def edit
  end

  # POST /usercodes
  # POST /usercodes.json
  def create
    @usercode = Usercode.new(code: params[:code], user_id: session[:user_id])
    puts @usercode
    respond_to do |format|
      if @usercode.save
        format.html { redirect_to @usercode, notice: 'Usercode was successfully created.' }
        format.json { render :show, status: :created, location: @usercode }
      else
        format.html { render :new }
        format.json { render json: @usercode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usercodes/1
  # PATCH/PUT /usercodes/1.json
  def update
    respond_to do |format|
      if @usercode.update(usercode_params)
        format.html { redirect_to @usercode, notice: 'Usercode was successfully updated.' }
        format.json { render :show, status: :ok, location: @usercode }
      else
        format.html { render :edit }
        format.json { render json: @usercode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usercodes/1
  # DELETE /usercodes/1.json
  def destroy
    @usercode.destroy
    respond_to do |format|
      format.html { redirect_to usercodes_url, notice: 'Usercode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usercode
      @usercode = Usercode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usercode_params
      params.require(:usercode).permit(:code, :user_id)
    end
end

app/helpers/usercodes_helper.rb
module UsercodesHelper
end

app/views/usercodes/_form.html.erb
<%= form_for(@usercode) do |f| %>
  <% if @usercode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usercode.errors.count, "error") %> prohibited this usercode from being saved:</h2>

      <ul>
      <% @usercode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_area :code %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usercodes/edit.html.erb
<h1>Editing Usercode</h1>

<%= render 'form' %>

<%= link_to 'Show', @usercode %> |
<%= link_to 'Back', usercodes_path %>

app/views/usercodes/index.html.erb
<%$i=1%>

<% @usercodes.each do |repo| %>


<div id="code-saved" class=" row container ">

  
  <h3> Repo ID: <%= $i %></h3>
  <div id="code">
  <p> <%= repo.code %></p>
  </div>
  <% $i+=1 %>
 
</div>


<% end %>

app/views/usercodes/new.html.erb
<h1>New Usercode</h1>

<%= render 'form' %>

<%= link_to 'Back', usercodes_path %>